version: "3.9"

services:
  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: "onsite_admin"
      POSTGRES_PASSWORD: "onsite"
      POSTGRES_DB: "onsite"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
